(()=>{var i=class{constructor(e){this.element=document.createElement(e)}withID(e){return this.element.id=e,this}withHTML(e){return this.element.innerHTML=e,this}withText(e){return this.element.innerText=e,this}withClasses(e){return this.element.classList.add(...e),this}withStyles(e){for(let n in e)this.element.style[n]=e[n];return this}withAttributes(e){for(let n in e)this.element[n]=e[n];return this}getElement(){return this.element}};var p=".ytp-button",m="yt-navigate-start",f="ytp-left-controls",g="ytp-right-controls";var I="yt-utils-loopControl",w={ON:"#ff0033",OFF:"#ffffff"},v=t=>`
        <svg xmlns="http://www.w3.org/2000/svg" width='24' height='24' viewBox="0 0 48 48"><title>yt-utils-loopIcon</title>
            <g class="nc-icon-wrapper" fill="${t?w.ON:w.OFF}">
                <path d="M24 8V2l-8 8 8 8v-6c6.63 0 12 5.37 12 12 0 2.03-.51 3.93-1.39 5.61l2.92 2.92C39.08 30.05 40 27.14 40 24c0-8.84-7.16-16-16-16zm0 28c-6.63 0-12-5.37-12-12 0-2.03.51-3.93 1.39-5.61l-2.92-2.92C8.92 17.95 8 20.86 8 24c0 8.84 7.16 16 16 16v6l8-8-8-8v6z"/>
            </g>
        </svg>
    `,b=(t,e)=>{let n=new i("div").withID(I).withHTML(v(t.loop)).withClasses([p]).withStyles({display:"flex",justifyContent:"center",alignItems:"center",opacity:.9,transition:"0.1s"}).getElement();n.addEventListener("click",()=>{t.loop=!t.loop}),new MutationObserver(o=>{o.forEach(r=>{r.type!=="attributes"||r.attributeName!=="loop"||(n.innerHTML=v(t.loop))})}).observe(t,{attributes:!0}),e.insertBefore(n,e.childNodes[3])},C=b;var c={ControlArea:"yt-utils-speedControlArea",Display:"yt-utils-speedDisplay",LeftChevron:"yt-utils-speedLeftChevron",RightChevron:"yt-utils.speedRightChevron"},E=.5,k=.5,M=4,L=t=>`
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 48 48"><title>yt-utils-chevron</title>
        <g class="nc-icon-wrapper" fill=${t||"#ffffff"}>
            <path d="M20 12l-2.83 2.83L26.34 24l-9.17 9.17L20 36l12-12z"/>
        </g>
    </svg>
`,P=(t,e)=>{let n=t.playbackRate,s=new i("div").withID(c.ControlArea).withStyles({display:"flex"}).getElement();e.insertBefore(s,e.childNodes[6]);let o=new i("div").withID(c.LeftChevron).withHTML(L()).withStyles({display:"flex",justifyContent:"center",alignItems:"center",opacity:0,transform:"rotate(180deg)"}).getElement();o.addEventListener("click",()=>{t.playbackRate>k&&(t.playbackRate-=E)}),s.appendChild(o);let r=new i("p").withID(c.Display).withText(t.playbackRate.toFixed(1)+"x").getElement();r.addEventListener("click",()=>t.playbackRate=1),s.appendChild(r);let l=new i("div").withID(c.RightChevron).withHTML(L()).withStyles({display:"flex",justifyContent:"center",alignItems:"center",opacity:0}).getElement();l.addEventListener("click",()=>{t.playbackRate<M&&(t.playbackRate+=E)}),s.appendChild(l),t.addEventListener("durationchange",a=>{a.target.playbackRate=n});let u;s.addEventListener("mouseover",()=>{u&&clearTimeout(u),o.style.opacity=1,l.style.opacity=1}),s.addEventListener("mouseleave",()=>{u=setTimeout(()=>{o.style.opacity=0,l.style.opacity=0},3e3)}),t.addEventListener("ratechange",a=>{n=a.target.playbackRate,r.innerText=a.target.playbackRate.toFixed(1)+"x"})},x=P;var R="yt-utils-pipBtn",d=t=>`
    <svg width="36" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><title>yt-utils-pip</title>
    <path d="M20 4H4C2.89543 4 2 4.89543 2 6V18C2 19.1046 2.89543 20 4 20H20C21.1046 20 22 19.1046 22 18V6C22 4.89543 21.1046 4 20 4Z" stroke="${t}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    <path d="M20 13H15C13.8954 13 13 13.8954 13 15V18C13 19.1046 13.8954 20 15 20H20C21.1046 20 22 19.1046 22 18V15C22 13.8954 21.1046 13 20 13Z" stroke="${t}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>   
`,h=!1,B=(t,e)=>{if(!document.pictureInPictureEnabled)return;h=!0;let n=new i("div").withID(R).withHTML(d("white")).withClasses([p]).withStyles({display:"inline-flex",justifyContent:"center",alignItems:"center",cursor:"pointer",transform:"translateY(-12px) translateX(-2px) rotateX(180deg)"}).getElement();e.insertBefore(n,e.childNodes[5]),n.addEventListener("click",()=>{h?document.pictureInPictureElement&&document.exitPictureInPicture():t.requestPictureInPicture(),h=!h}),t.addEventListener("enterpictureinpicture",()=>{n.innerHTML=d("red")}),t.addEventListener("leavepictureinpicture",()=>{n.innerHTML=d("white")})},D=B;var y;document.getElementsByTagName("video").length>0?T():document.addEventListener(m,()=>{y||location.pathname!=="/watch"||T()});function T(){if(y||location.pathname!=="/watch")return;y=!0;let t=document.getElementsByTagName("video")[0],e=document.getElementsByClassName(f)[0],n=document.getElementsByClassName(g)[0];C(t,e),x(t,e),D(t,n)}})();
